/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e8d706bea5437d9242140603abd8ee28)
interface __BaseEnv_Env {
	PAGE_VIEWS: AnalyticsEngineDataset;
	ASSETS: Fetcher;
	ACCESS_KEY_ID: string;
	SECRET_ACCESS_KEY: string;
	ENDPOINT: string;
	CF_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_KEY_ID" | "SECRET_ACCESS_KEY" | "ENDPOINT" | "CF_TOKEN">> {}
}
